### ISSUE TITLE
Portrait orientation causes crash when launching from bottom picker library

### ISSUE THREAD

**Issue by aleedy** [ParkSangGwon/TedRxOnActivityResult#5]
Found this using your bottom picker library in my project.  You can see comments here: https://github.com/ParkSangGwon/TedBottomPicker/issues/93

On a Android O and higher, transparent activities cannot request orientation as discussed here: 
https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o

**Comment by ParkSangGwon** [comment]
@theGnartist Thanks for your PR and reporting.

**Comment by aleedy** [comment]
Excellent thanks for taking care of this!
